### ISSUE TITLE
make portaudio dependency optional

### ISSUE THREAD

**Issue by Maskedman99** [funilrys/aur-cava#1]
Currently portaudio is a required dependency, would be nice if it's changed to optional dependency as I am using ALSA and don't want to install portaudio. 

> Required components:
        FFTW
        libtool
        automake
        build-essentials
        iniparser
        Recomended components:
        ncursesw dev files (bundled in ncurses in arch)
        ALSA dev files, or
        Pulseaudio dev files, or
        Portaudio, or
        Sndio

Quoted from https://github.com/karlstav/cava/blob/master/README.m

**Comment by funilrys** [comment]
Hey @Maskedman99, go ahead with the PR 👍🏾 

I'll be glad to review and merge it!

**Comment by Maskedman99** [comment]
@funilrys I've submitted a PR
