### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by Aqa-Ib** [funilrys/aur-cava#15]
AUR "cava" package does not build. However "cava-git" package does build fine.

[cava.log](https://github.com/funilrys/aur-cava/files/15295395/cava.log)

Thanks.

**Comment by funilrys** [comment]
Interesting, I can't reproduce this ... Is that on a fresh install ?

**Comment by funilrys** [comment]
*Correction: I can reproduce it.

**Comment by funilrys** [comment]
Should be fixed by latest release.

**Comment by Aqa-Ib** [comment]
Thank you very much. I wish you the best.
